### ISSUE TITLE
Missing capital letters in weights 200-300

### ISSUE THREAD

**Issue by karhuton** [Outfitio/Outfit-Fonts#12] opened 2022-02-28 09:26 UTC
Great font! Noticed these light-weight styles are partially working at least in Google Fonts versions:

<img width="1379" alt="Näyttökuva 2022-2-28 kello 10 23 51" src="https://user-images.githubusercontent.com/15217199/155957722-ab5818c1-da11-4d95-85a9-ca3b30817b95.png">

**Comment by andyfitz** [comment] 2022-06-15 05:56
Hey @karhuton , sorry for the lag, we couldn't reproduce this issue and it seems google fonts has all capitals in their version.  

Of course if you use our upstream version you get a lot of the extra features including alternated etc.


Closing this issue as the concern seems to be rectified

**Closed by andyfitz** 2022-06-15 05:56 UTC
