### ISSUE TITLE
Italic

### ISSUE THREAD

**Issue by cadday** [Outfitio/Outfit-Fonts#9] opened 2021-12-14 09:44 UTC
The font is awesome but it seems like there is no italic version which is a bit of a problem when used in web development.
Will there be an italic version?

**Comment by andyfitz** [comment] 2021-12-17 05:17
Not in the short-term but true italics and monospace variants are firmly on the wish list at Outfit

**Comment by andyfitz** [comment] 2022-06-15 05:59
Closing this issue as it's a duplicate of 
https://github.com/Outfitio/Outfit-Fonts/issues/4

**Closed by andyfitz** 2022-06-15 05:59 UTC
